### ISSUE TITLE
improve downloading of existing predictions

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/portalcasting#107]
the current approach is file-by-file and ends up sending a lot of calls to GitHub
it would be nice to simplify the request/download of the files

**Comment by juniperlsimonis** [comment]
@ethanwhite this is the spot where i started an issue on the downloading hiccups before.

this is the function where the downloading actually happens:
https://github.com/weecology/portalcasting/blob/master/R/prepare_predictions.R

**Comment by ethanwhite** [comment]
My initial thought on this is to grab them from Zenodo instead of GitHub. If we grab from the `forecasts` archive (https://zenodo.org/record/3246517) it's only 15 MB in a zip, unzip and navigate. That said, I seem to recall that portalr is currently pulling from GitHub for some reason, so let me know if there's a limit to using Zenodo.

We could do something similar from GitHub using the API to list the most recent release, downloading the zip of the entire repo, and then unzipping and navigating.

I personally prefer Zenodo if there aren't major barriers.

**Comment by juniperlsimonis** [comment]
yeah i imagine we can mirror what portalr does, which can pull from multiple sources depending on what the user wants.

**Comment by juniperlsimonis** [comment]
done in #129
