### ISSUE TITLE
Add or swap in shorter run version of `portalcast` in Getting Started

### ISSUE THREAD

**Issue by ethanwhite** [weecology/portalcasting#117]
Running `portalcast()` is pretty slow and since it's a command listed in the Getting Started vignette folks are likely to just run it (like I just did). It's probably useful to provide (either as the only option or an alternative) one that produces a quicker run time for those just starting to get involved in the project.

**Comment by juniperlsimonis** [comment]
oooh this is a very good point.

currently, the "factory fresh" versions of the functions are set up to run in the "real" pipeline without needing to change any arguments. naturally, that's a BIG run, which a new user wouldn't want to do to start.

there are a few possible avenues to address this, and i'm wondering what your feelings are on what the default behavior should be (no models, a single simple model, all the models, something else?) 

personally, i'd favor keeping the default options the same, but then setting it up so a simpler run could be done very easily (with a single argument in, rather than the pipe of control list functions that's presently required for the user).

**Comment by ethanwhite** [comment]
> personally, i'd favor keeping the default options the same, but then setting it up so a simpler run could be done very easily (with a single argument in, rather than the pipe of control list functions that's presently required for the user).

This sounds good to me. I'd actually started opening an issue about surfacing some of the key arguments from `all_options` as direct arguments in `portalcast`, but then I flinched because I thought it might be tricky under the surface.

**Comment by juniperlsimonis** [comment]
totally on that. it's a lot less tricky now that all the parts have been connected (now that all the threads are connected and the arguments/variables have consistent names throughout, i can follow usage more simply and set this kind of stuff up without as much of a risk of wack-a-mole problems), so if there are arguments that you're interacting with at the top level that would be nicer to have more directly, totally let me know.

**Comment by ethanwhite** [comment]
Will do. `models` is definitely the number one priority for me as a "I want to add a new model" user.

**Comment by juniperlsimonis** [comment]
done in #129
