### ISSUE TITLE
tighten down testing

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/portalcasting#124]
current testing is far too hefty for cran.

**Comment by ethanwhite** [comment]
The other option here is to flag the long-running tests to not run on CRAN. That said, there is value in unit tests that run relatively quickly, so if there are natural places to speed things up that's great, but we often end up turning things off for CRAN that we want to actually run on CI, so that's a totally standard thing to do (and something that can typically be done more quickly than trimming run time on tests more generally).

**Comment by juniperlsimonis** [comment]
other thing to note about the testing... it was excessive given the structure of the codebase. now that i have a better handle on where things connect, i can eliminate redundant tests.

**Comment by juniperlsimonis** [comment]
addressed w #129
