### ISSUE TITLE
fix edge case in CPEDM

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/portalcasting#177]
Hey @ha0ye , it looks like the GPEDM is the culprit for the warning messages on the website, as it's giving `NA` values for error bounds when there prediction is on the boundary (all 0s all the time). We definitely have those situations given that we're forecasting for the whole lot of species, so this is something we'll want to fix. Can you patch it appropriately within the function for the model?
![image](https://user-images.githubusercontent.com/23511502/73383756-ccf2d400-427e-11ea-90d0-293ba580c9d5.png)

**Comment by ha0ye** [comment]
Hmm, I'll take a look. Thanks for the screenshot, which will help identify where the problem arises. 

I'm wondering if perhaps the issue occurs because the time series might be 0 or mostly 0, and so the model fails to get any estimate on the errors. In that case, I might need to talk with you more about what the model should output for those edge cases...

**Comment by juniperlsimonis** [comment]
for sure for sure

yeah, totally hear you on what exactly we want models to return on the really boundary conditions like that. 

for the time being, i've gotten the warnings suppressed in the website build (next time it gets made by a cron), and it's not noticeable in the figure so there's no major rush.

**Comment by juniperlsimonis** [comment]
closing this specific issue as it appears moot under #220 
although tagging it here in case there is a persistent problem with the code in the package that isn't caught in the general update
