### ISSUE TITLE
fix pkgdown github action

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/portalcasting#206]
not sure what's causing the deploy step to time out... working so slowly

**Comment by ethanwhite** [comment]
I'm working on optimizations for the CI to help with this, but fundamentally the problem is with the docs build itself, which is just extremely slow (it took me over 30 minutes locally to get through building `jags_ss.html`). This seems to be due primarily to the large number of times that `setup_dir()` (which is slow) gets called in the examples. The `jags_ss` example is particularly slow, especially on the GitHub Actions infrastructure (it's building this page for at least 25 minutes now), which makes sense since it's presumably not designed for intensive compute.

So, I'll see if my current improvement will get this fast enough for the build to succeed, but even if it does it will I think the ultimate solution here is:

1. Either #195 or a change in how examples are handled (e.g., is there a way to ensure that `setup_dir()` is run once before docs generation and then not include it in the examples).

and

2. Either removing the JAGS example or replacing it with something that's really simple and fast.

**Comment by ethanwhite** [comment]
Confirming that the build was continuing to progress, just very slowly, and eventually timed out after 6 hours: https://github.com/ethanwhite/portalcasting/runs/1984318888?check_suite_focus=true
