### ISSUE TITLE
Model Output getting overwritten

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/portalcasting#213]
issue with overwriting model output in portal predictions

not sure if this is a portalcasting or infrastructure issue, but if you look at the commit logs, the most recent files are just being overwritten, rather than there being new files

https://github.com/weecology/portalPredictions/commits/main/casts

**Comment by ethanwhite** [comment]
Good catch. Something we should probably add a test for.

Error first appears here in https://github.com/weecology/portalPredictions/commit/0ce29a05fe2b4be366f4086f2236ea5a85aacf9f, which doesn't appear to correspond to changes in portalPredictions (last change there was 12 days and two published forecasts prior). So that would point to:

1. A delayed change to https://github.com/weecology/portalPredictions/commit/d84b751f14c7a7c486767b06be43553ab0b5f395 in the code on HiPerGator
2. A change on HiPerGator unrelated to https://github.com/weecology/portalPredictions/commit/d84b751f14c7a7c486767b06be43553ab0b5f395
3. A change in portalcasting

The last portalcasting release (https://github.com/weecology/portalcasting/releases/tag/v0.21.1) did occur the day before this behavior started happening, so that feels like the first place to check assuming that it was associated with an update to the docker container. @juniperlsimonis are you seeing different behavior in portalcasting locally?

**Comment by juniperlsimonis** [comment]
circling back on this, it looks like this issue has been addressed. 
locally it operates properly now, as well.
thanks to whomever amongst us fixed this!
