### ISSUE TITLE
what else should come in the sandbox?

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/portalcasting#230]
What other items would make it helpful to sandbox models?

Not restricted to arguments in a function, much more broadly speaking.
functions, data products, templates, api points etc.

i'm working to make the process as user-friendly and hands-on as possible, so really think of this issue as a brainstorming list!

@patdumandan @skmorgane @gmyenni  @ha0ye 

- [x] dataset template: a bare bones example of a new dataset 
- [x] model template: a  bare bones example of a new model
- [x] small set of output files: examples of the archive without the **whole** archive

**Comment by patdumandan** [comment]
Hi @juniperlsimonis , as per our conversation yesterday, things that might be useful to make sandboxing more user-friendly are:
1. relaxing the default options for creating rodent data tables through the rodents_control function. Right now, when I do something like `rodents_control(name = "PP_controls", level = "Treatment", species="PP", interpolate=FALSE,
                                    treatment = c("control", "exclosure"), output="abundance", 
                                    arg_checks = ``FALSE),` what I get is a total of PPs in both controls and exclosures. Since I want to have 
those data as separate values but be run with the same model, I am unable to do so.
2. having the option to set the start and end of the forecast in the portalcast function be in a year format. So instead of having to set start_moon= XX and end_moon=XX, something like start_year=XX, end_year=XX might be useful. (or be able to switch around so like having an argument in portalcast that would allow the user to choose if they want to forecast in terms of moons or years or months, and then based on that option, be able to set the start/end.

**Comment by juniperlsimonis** [comment]
templates added in #304
